# roles/mailserver/defaults/main.yml
---
postfix_myhostname: 'prdx-mail101.ziyotek1.local'

postfix_mydomain: 'ziyotek1.local'

postfix_home_mailbox: 'mail/'

spamassassin_packages:
  - spamassassin

clamav_packages:
  - clamav-server
  - clamav-data
  - clamav-update
  - clamav-filesystem
  - clamav
  - clamav-scanner-systemd
  - clamav-devel
  - clamav-lib
  - clamav-server-systemd
postfix_mynetwork:
  - 192.168.32.0/24
postfix_ldap: false
